### PR TITLE
First pass at gem

### PR DESCRIPTION
**Pull request by matt-hwy1**

### CODE REVIEW

**Comment by matt-hwy1** [comment]
@defeated It won't let me assign anyone from Litmus, so here is my PR for this. Please let me know if you need me to structure this PR differently.

**Comment by demoore** [comment]
@matt-hwy1 Did you mean to PR this against a fork?

**Comment by defeated** [comment]
@demoore hi Dylan! This may have been opened a little prematurely - but yes, we are working to add AciveJob support ("deliver_later") to SendWithUs mailers (for parity with expected ActiveMailer methods & behavior)

Do you prefer to keep this open (we can squash and debase before final review) or have us submit a new PR when ready?

**Comment by demoore** [comment]
@defeated No worries — that sounds great! By all means keep it open 😄

**Comment by matt-hwy1** [comment]
I'm replacing this PR with the "real" one. This was inadvertent and defunct now.

**Pull request closed without merging**
