### PR TITLE
Inherit defaults

### PR DESCRIPTION
**Pull request by EvgeniyShelest**

### CODE REVIEW

**Comment by demoore** [comment]
Hey @EvgeniyShelest , what was the impetus behind this? Let me know how this would be useful. Thanks! :smile:

**Comment by bmulholland** [comment]
@EvgeniyShelest Great stuff here. One potential future bug is that changing the defaults of a child class could impact the defaults for a parent class. That doesn't happen here because `default` does a merge, but that implementation could change in the future. Could you dup the defaults in `inherited` just to be safe?

**Comment by EvgeniyShelest** [comment]
Hey @demoore, we have a lot of mailers. We have grouped them by its feature and goals. All mailers are   inherited from common mailer that has common defaults. But in some group we need to override common defaults by custom. So by inheritance we just follow DRY principle.

**Comment by EvgeniyShelest** [comment]
https://gist.github.com/EvgeniyShelest/d0d092da08d3803c98ec

**Comment by EvgeniyShelest** [comment]
Hey @bmulholland , I made some experiment. I changed implementation of `default` method. Now it just set `@defaults`. And you can see that Sub `@defaults` doesn't impact Base `@defaults` in gist:
https://gist.github.com/EvgeniyShelest/d0d092da08d3803c98ec
Don't worry, Base `@defaults` will not be overridden.
In method `inherited` I just read Base `@defaults`.
 By the way this case is covered by tests.
Thanks.

**Comment by bmulholland** [comment]
@EvgeniyShelest Good stuff! Thanks for looking into that. LGTM :+1:

**Comment by demoore** [comment]
Looks good guys. Thanks!

**Pull request merged**
