### PR TITLE
Adding perform_delivery option so we can cancel the email sending

### PR DESCRIPTION
**Pull request by Ricardonacif**
Adding perform_delivery option so we can cancel the email sending.

### CODE REVIEW

**Comment by Ricardonacif** [comment]
@demoore makes sense?

**Comment by demoore** [comment]
@Ricardonacif I get what's going on, but I don't understand why. It looks like you're passing a boolean in, so rather than modify the client, can't you just check before you make the send call?

**Comment by Ricardonacif** [comment]
@demoore the problem is, if I enqueue an email with sidekiq like ```EmailClass.enqueue_in(3.days).send_email```, and in 3 days I wanna verify if I still need to send the email, I think its valuable to be able to cancel the delivery if it doesn't make sense anymore. On ActionMailer itself I'm able to do that, but if I simply return the method or don't call 

```
    mail(
      email_id: "xxxxx",
      recipient_address: user.email
    )
```

it will raise an exception. With this pull request I'm able to do the following

```ruby
    mail(
      email_id: "xxxxx",
      recipient_address: user.email,
      perform_delivery: false
    )
```

**Comment by demoore** [comment]
@Ricardonacif this seems out of scope of the client. Rather than using the client, wouldn't stopping the job in sidekiq be better?

**Comment by Ricardonacif** [comment]
@demoore there's no way of doing on Sidekiq because it simply calls the delay method that will call the mailer class method itself when its time to send the email (there's no job/worker code, just the sendwithus mailer method being called).

I don't agree that this is out of scope of the client. If this clients has the integration with Sidekiq explicitly on README.me, and it tries to mimic ActionMailer behaviors (which has this feature for canceling delivery), I see plenty of use cases for that. No?

**Comment by bmulholland** [comment]
@Ricardonacif Would you mind adding a link to the documentation for the ActionMailer feature that this mirrors? It would be good to ensure that they match, but my Google-fu is failing me.

**Comment by Ricardonacif** [comment]
@bmulholland actually the sintax is 
```ruby
class SomeMailer < ActionMailer::Base
  def some_method
    if @some_email_data.nil?
      self.message.perform_deliveries = false
    else
      mail(...)  
    end  
  end
end

```

Take a look at the second answer on http://stackoverflow.com/questions/6550809/rails-3-how-to-abort-delivery-method-in-actionmailer . Maybe I can change the PR so if we don't call mail it won't send (and won't raise any exception). Which way you think is better?

**Comment by bmulholland** [comment]
@Ricardonacif  Per http://api.rubyonrails.org/classes/ActionMailer/Base.html#class-ActionMailer::Base-label-Configuration+options, `perform_deliveries` is intended to be used for testing. Looks like Rails has gone the way you're suggesting: don't raise an error if mail isn't called. That seems like a good approach to me!

**Comment by Ricardonacif** [comment]
@bmulholland cool, code updated :)

**Comment by bmulholland** [comment]
:+1:

**Comment by Ricardonacif** [comment]
:)

**Comment by demoore** [comment]
@Ricardonacif @bmulholland Thanks guys this looks great! @Ricardonacif Could you add an example of how to use it in the README? After that I'll merge it in :smile_cat:

**Comment by Ricardonacif** [comment]
@demoore sure! Added :)

**Comment by demoore** [comment]
@Ricardonacif Looks great! Merging now.

**Pull request merged**
